FROM falkordb/falkordb:edge AS falkordb

FROM redis as redis

WORKDIR /data

RUN apt update && apt install libgomp1 -y

COPY ./cluster-conf.conf /data/node.conf

COPY ./cluster-script.sh /data/cluster-script.sh

COPY --from=falkordb /FalkorDB /FalkorDB

ENTRYPOINT ["/data/cluster-script.sh"]